### ISSUE TITLE
[BUG]  TypeError: browserType.connect: Invalid URL

### ISSUE THREAD

**Issue by sathishwaranb** [microsoft/playwright-testing-service#71] opened 2023-11-06 10:02 UTC
### System info
- Playwright Version: [1.39.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});

```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Through Playwright CLI]
- Executed Below Code
- [npx playwright test --config=playwright.service.config.ts --workers=20]

**Expected**

Test to be execute successfully.
<img width="652" alt="ErrorImage" src="https://github.com/microsoft/playwright/assets/150015067/a9296bb9-8ceb-4aad-bfb5-08866fb4874c">
 

**Actual**

    TypeError: browserType.connect: Invalid URL
    =========================== logs ===========================
    <ws preparing> retrieving websocket url from undefined?cap={"os":"linux","runId":"2023-11-06T07:13:35.187Z"}
    ============================================================

AB#1913593

**Comment by mxschmitt** [comment] 2023-11-06 12:31
Moved to the right repo and re-opened.

**Comment by sathishwaranb** [comment] 2023-11-06 12:39
<img width="439" alt="ProjectFolderScreenshot" src="https://github.com/microsoft/playwright-testing-service/assets/150015067/08bd68b0-c177-489d-8e54-e955ad5c6e6d">
.env file placed along with playwright.service.config file.. please refer the attached screenshot 'ProjectFolderScreenshot'

**Comment by mxschmitt** [comment] 2023-11-06 12:43
Did you uncomment:

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();
 
in your config? Otherwise it won't read from the .env file.

**Comment by sathishwaranb** [comment] 2023-11-06 13:29
![image](https://github.com/microsoft/playwright-testing-service/assets/150015067/4cbf5c7d-7322-439e-8e7b-68b805540c6a)
Uncommented the config file.. but getting the same error
![image](https://github.com/microsoft/playwright-testing-service/assets/150015067/6ce85b55-0f32-4987-a431-4957939c7765)

**Comment by puagarwa** [comment] 2023-11-06 16:24
@sathishwaranb its a clear case of env variable not being set. It could depend upon your client machine, environment on why dotenv is not working as expected.

Two things
- please share your playwright.service.config.ts file if you can
- You could set environment variable https://www.twilio.com/blog/how-to-set-environment-variables-html explictly to make progress and root cause the issue further. 
- You can use our sample available in repo and try it out

**Comment by sathishwaranb** [comment] 2023-11-07 05:58
below is my playwright.service.config file details and I have created .env fie with variable PLAYWRIGHT_SERVICE_URL & PLAYWRIGHT_SERVICE_ACCESS_TOKEN

/*
* This file enables Playwright client to connect to remote browsers.
* It should be placed in the same directory as playwright.config.ts.
* The file is temporary for private preview.
*/

import { defineConfig } from '@playwright/test';
import config from './playwright.config';
import dotenv from 'dotenv';

// Define environment on the dev box in .env file:
//  .env:
//    PLAYWRIGHT_SERVICE_ACCESS_TOKEN=XXX
//    PLAYWRIGHT_SERVICE_URL=XXX

// Define environment in your GitHub workflow spec.
//  env:
//    PLAYWRIGHT_SERVICE_ACCESS_TOKEN: ${{ secrets.PLAYWRIGHT_SERVICE_ACCESS_TOKEN }}
//    PLAYWRIGHT_SERVICE_URL: ${{ secrets.PLAYWRIGHT_SERVICE_URL }}
//    PLAYWRIGHT_SERVICE_RUN_ID: ${{ github.run_id }}-${{ github.run_attempt }}-${{ github.sha }}

dotenv.config();

// Name the test run if it's not named yet.
process.env.PLAYWRIGHT_SERVICE_RUN_ID = process.env.PLAYWRIGHT_SERVICE_RUN_ID || new Date().toISOString();

// Can be 'linux' or 'windows'.
const os = process.env.PLAYWRIGHT_SERVICE_OS || 'linux';

export default defineConfig(config, {
  // Define more generous timeout for the service operation if necessary.
  // timeout: 60000,
  // expect: {
  //   timeout: 10000,
  // },
  workers: 20,

  // Enable screenshot testing and configure directory with expectations.
  // https://learn.microsoft.com/azure/playwright-testing/how-to-configure-visual-comparisons
  ignoreSnapshots: false,
  snapshotPathTemplate: `{testDir}/__screenshots__/{testFilePath}/${os}/{arg}{ext}`,
  
  use: {
    // Specify the service endpoint.
    connectOptions: {
      wsEndpoint: `${process.env.PLAYWRIGHT_SERVICE_URL}?cap=${JSON.stringify({
        // Can be 'linux' or 'windows'.
        os,
        runId: process.env.PLAYWRIGHT_SERVICE_RUN_ID
      })}`,
      timeout: 30000,
      headers: {
        'x-mpt-access-key': process.env.PLAYWRIGHT_SERVICE_ACCESS_TOKEN!
      },
      // Allow service to access the localhost.
      exposeNetwork: '<loopback>'
    }
  }
});

**Comment by puagarwa** [comment] 2023-11-07 07:38
This service config looks good and that means most likely issue is somewhere in dotenv configuration, as i mentioned earlier, for now please set env variable directly via other means https://www.twilio.com/blog/how-to-set-environment-variables-html  to unblock yourself and then we need to debug dotenv issue seperately and for that we may require more detail around your setup and enviroment to be able to repro and debug it.

**Comment by sathishwaranb** [comment] 2023-11-07 12:14
Thanks for solution. its working fine after setting the env variable.

**Comment by vvs11** [comment] 2023-11-07 18:35
I am closing this issue. Feel free to re-open if you face any issue.

**Closed by vvs11** 2023-11-07 18:35 UTC
