### ISSUE TITLE
[BUG]: ERROR: No tests found when running playwright-testing-service in an existing playwright project

### ISSUE THREAD

**Issue by joshcv2112** [microsoft/playwright-testing-service#73] opened 2023-11-16 20:13 UTC
**Describe the bug**
When trying to run a playwright test from an existing project the following error is shown: "ERROR: No tests found". (no additional error details are logged).

I have two playwright projects on my machine that I have tried to run with playwright testing service. Let's call them Project A and Project B. Project A is our legacy playwright testing repo, we've had it for 2+ years. Project B is a fresh project I started for the sole purpose of testing the playwright testing service, this was created with boilerplate test file, `npm init playwright@latest`.

In Project B, I had no issue at all when trying the playwright testing service, I was able to add the `playwright.service.config.js` and run the boilerplate tests using the service. Since this was a new repo there was no pre-existing config to go along with.

In Project A, I brought in the same boilerplate test script, put it in the same `/tests` directory, added the `playwright.service.config.js` to the project root, then tried running the tests with the playwright testing service. This is where I see the "No tests found" error. Since Project A is older and has a `playwright.config.js` file alongside the new `playwright.service.config.js` file. I imagine the issue has to do with some conflicting configurations, but I can't be sure.

**To Reproduce**
1. From a playwright test project, include the two config files attached below, as well as the boilerplate test file.
2. Run a test using: `npx playwright test --config=playwright.service.config.js --workers=6` (assuming all required testing-service variables are set)
3. See error

**Expected behavior**
Test should run on playwright testing service without error.

**Screenshots**
<img width="423" alt="Project File Structure" src="https://github.com/microsoft/playwright-testing-service/assets/12425446/0a6458df-c243-476a-9c07-b3a12a9f8330">
<img width="882" alt="test error" src="https://github.com/microsoft/playwright-testing-service/assets/12425446/f7a65a3a-b1b4-4be7-95e7-c55c35856fe8">
[playwright.config.js.txt](https://github.com/microsoft/playwright-testing-service/files/13382994/playwright.config.js.txt)
[playwright.service.config.js.txt](https://github.com/microsoft/playwright-testing-service/files/13382995/playwright.service.config.js.txt)

**Setup information (please complete the following information):**
Follow the steps on playwright.microsoft.com to have required env vars to run the playwright testing service

AB#1918655

**Comment by puagarwa** [comment] 2023-11-17 10:07
Hi @joshcv2112 I can spot one issue in your folder structure, your test file example.spec.ts is at root level but by default playwirght expect tests files to be inside ./tests/ folder , you have two options here
- either create a new folder tests and move this file inside
- or in playwright.config.js add this line testDir: './'

**Comment by joshcv2112** [comment] 2023-11-17 16:20
The example.spec.js file is in the root of the test folder, alongside the other tests sub-folders (function, sandbox, page, workflow). It might be hard to see because the indentation is very subtle.

**Comment by puagarwa** [comment] 2023-11-17 18:09
Hi @joshcv2112 thanks for pointing it out, so test files are actually inside tests folder, so this seems fine.

Good part is, i am able to repro the issue at my end using your config and i am looking into possible solution. Though i am still trying to find proper solution but meanwhile, you could use this attached modified playwright.config file to run tests against service mode. I have integrated service into it.

[playwright.config.js.txt](https://github.com/microsoft/playwright-testing-service/files/13395148/playwright.config.js.txt)
With this, you can run your test with `npx playwright test --worker=6` since i have already merged service integration changes in same config. 
if you want to maintain local and service configs, one way is to use env variable say MPT_SERVICE and control connectOption in config with this env variable (`connectOptions: !process.env.MPT_SERVICE ? undefined :{...`})

**Comment by puagarwa** [comment] 2023-11-20 05:12
Hi @joshcv2112 I found the root cause of this issue and it turned out to be small bug in playwright client code, though this fix will only be available in 1.41 next month but we have minor workaround for it to get you going.

Fix in playwright Runner: https://github.com/microsoft/playwright/pull/28224
Issue Description: There is bug which set projects to null when merging multiple configs which doesnt have any project. If any of the configs has atleast 1 project, this bug wont impact us. 

Workaround: In your config file, you can just add this empty list of projects and then it will work fine. like this projects: [{}]

Workaround i suggested in previous step is also valid workaround because i am merging service config inside your default config itself.

**Comment by joshcv2112** [comment] 2023-11-20 15:34
Hi, I tried adding projects: [{}] to the config file and that seems to have fixed "No Tests Found" error. Thanks for the help with this workaround!

**Closed** 2023-11-20 15:57 UTC
