### ISSUE TITLE
Quota increase request

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright-testing-service#60] opened 2023-10-20 13:36 UTC
## Quota Increase Request

**Quota to Increase:**
 I'm testing this out on my own personal website with my personal azure account. Setting up the service on CI I seemed to make a mistake with the working directory. Still not sure what it should be but what I put was wrong and tests failed. Reverting back to using shards instead of service and tests passed. This mistake used up all my billing minutes and was charged €3.68 for tests that failed due to a bad configuration. It means my trial is now over and can't continue to test the service. 

In image below bottom one was running the service with CLI and top one was on CI which I had to cancel workflow as it was taking so long and just failing.

<img width="1285" alt="Screenshot 2023-10-20 at 14 43 48" src="https://github.com/microsoft/playwright-testing-service/assets/13063165/05d429f3-5742-498b-9d78-fec185c8f211">

Using debs_obrien@yahoo.co.uk for azure account.

workspace is called testservice

so two things - how do I get the service to actually work and how do I test the service without being billed?

repo with what went wrong is here:
https://github.com/debs-obrien/debbie.codes/pull/454/commits/7c9c49e4a36f86d492853c66230cf4a8e6827923

[Specify which quota you would like to increase]

* [ ] Maximum number of workers for the workspace
* [ ] Maximum number of workspaces per subscription
* [ ] Throttling limits
* [ ] Other

 

**Business Justification:**

[Please provide a detailed business justification for the quota extension. Explain why this increase is necessary for your project or use case.]

**Requested New Quota Limit:**

[Specify the new quota limit you are requesting. Please be specific about the quantity or value (e.g., 60 workers per workspace, 5 workspaces per subscription etc.).]

**Additional Information:**

[Include any additional information that may be relevant to your request, such as project deadlines, the impact of the quota increase on your work, etc.]

**Setup Information:**

- **Subscription ID:** [Your Azure subscription ID]
- **Workspace ID:** [ID of the workspace where you want to request quota increase]

**Disclaimer:**

Please note that while we will do our best to accommodate your quota extension request, we may not be able to fulfill every request due to resource constraints. We will review your request and provide a response as soon as possible.

AB#1905525

**Comment by puagarwa** [comment] 2023-10-27 13:30
Hi @debs-obrien I forked your repo and able to repro the issue and able to make it working here is the PR https://github.com/debs-obrien/debbie.codes/pull/456

Test failure reason
- Timeouts getting browser: Due to workflow trying to get 80 workers whereas quota is only 20 hence timing out after 30s
- 5s timeout during action: Service we have more workers trying to access localhost from CI machine, individual operations can sometime takes more time, hence we need to increase timeout
- I played with your suite, and it seems like 8-12 worker is right tuning as we wont see much benefit going beyond it. Generally, this depend upon multiple factors like load on CI, webapp load

PS: I observe few tests are flaky even in local mode as well.

Let me know if you need help. We could increase your quota to high value if still needed.

**Comment by johnsta** [comment] 2023-11-07 01:53
Hi @debs-obrien, if the causes identified by @puagarwa didn't resolve your issue, please let us know. Closing this for now.

We appreciate your feedback regarding the possibility of failed test runs consuming your free trial minutes. In response, we're updating our documentation to better guide first-time users. As a new user, we recommend starting with a small number of tests to confirm that your configuration works correctly before scaling up to more extensive testing. This approach will help build your confidence in using the service. 

Additionally, if you encounter any issues or concerns with billing, you can create a support ticket in the Azure Portal. The following steps will kick off the process:
1. Go to https://aka.ms/mpt/help-and-support
2. Click **Create a support request**
3. For **Issue type**, select **Billing**.

**Closed by johnsta** 2023-11-07 01:53 UTC
